### ISSUE TITLE
License

### ISSUE THREAD

**Issue by frodrigo** [yhara/enumerable-lazy#3]
Please, can you add a license to your gem ?

**Comment by yhara** [comment]
Hi,

The license is MIT. I've updated README.

**Comment by postmodern** [comment]
Could you also release a new version? That way rubygems.org will display the MIT license. https://rubygems.org/gems/enumerable-lazy

**Comment by connorshea** [comment]
Yes please, this is causing license_finder to fail unless we set the license manually. New release would be appreciated!

**Comment by yhara** [comment]
Hi, 

I've released 0.0.2. https://rubygems.org/gems/enumerable-lazy

By the way I'm curious how people happened to find this gem, because it is no more necessary on Ruby >= 2.0.

@connorshea Are you using this gem in your project, or is there a gem which depends on enumerable-lazy gem?

**Comment by connorshea** [comment]
@yhara it's a dependency of mustermann19 which was used by Grape until very recently: https://github.com/ruby-grape/grape

**Comment by connorshea** [comment]
And thank you for the release!

**Comment by yhara** [comment]
@connorshea Got it! Thank you too :-)
